name: Test Action

on:
  push:
    branches: [ main]
    
jobs:
  
  build:
    
    runs-on: ubuntu-latest
    
    steps:
      
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version : 12
      - name: Check Commands
        run: pwd
        
        
        
      - name: Check ls
        run: ls
        
      - name: install surge 
        run: npm install -g surge
        
      - name: Deploy website on surge
        run: surge ./ wooden-lunch.surge.sh --token ${{secrets.MY_SECRET_SHAYAN}}
